version: "3"

volumes:

  vscode_server: null

services:
  rust:
    # NOTE: if you already built this, just use the already built image
    build:
      # NOTE: change to where the Dockerfile for python dev container is located
      context: .
      dockerfile: Dockerfile
    image: rust-dev
    volumes:
      - vscode_server:/home/vscode/.vscode-server
      # NOTE: change to where the code for python dev container is located
      - .:/home/vscode/${WORKDIR:-code}
    ports:
      - ${REST_PORT:-8000}:8000
    init: true
